services:
# api:
#   image: 'nancytec/eventhub-api'
#   build:
#     context: .
#     dockerfile: Dockerfile
#     # Only will build development stage from our dockerfile
#     target: development
#   volumes:
#     - /app/node_modules
#     - .:/usr/src/app
#   env_file:
#     - ./env/api.env
#   command: npm run start:dev
#   ports:
#     - "4000:5000"
#   depends_on:
#     - postgres
#     - redis
 postgres:
    image: postgres
    restart: always
    env_file:
      - ./env/postgres_db.env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
# redis:
#    image: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis:/data

volumes:
  postgres-data:
    driver: local
#  redis:
#    driver: local