export const events = {
  SUPPORT_CREATED: 'SUPPORT_CREATED',
  SUPPORT_UPDATED: 'SUPPORT_UPDATED',
  SUPPORT_STATUS_CHANGED: 'SUPPORT_STATUS_CHANGED',
  SUPPORT_STATUS_CLOSED: 'SUPPORT_STATUS_CLOSED',

  USER_CREATED: 'USER_CREATED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  VERIFICATION_TOKEN_REQUEST: 'VERIFICATION_TOKEN_REQUEST',
  ACCOUNT_VERIFIED: 'ACCOUNT_VERIFIED',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  EMAIL_CHANGED: 'EMAIL_CHANGED',
};

export const appInfo = {
  appName: 'EVENTHUB',
  appEmail: 'system@eventhub.com',
  companyName: 'EVENT MNGT',
  companyPhone: '+234-8138-234-786',
};

export const errors = {
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  FORBIDDEN_ERROR: 'ACCESS_DENIED_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  DATA_CONFLICT_ERROR: 'DATA_CONFLICT_ERROR',
  NOT_ACCEPTABLE_ERROR: 'NOT_ACCEPTABLE_ERROR',
  UNPROCESSABLE_DATA_ERROR: 'UNPROCESSABLE_DATA_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

export const roles = {
  ADMIN: 'ADMIN',
  REGULAR: 'REGULAR',
};
